name: RSS to Email

on:
  schedule:
    - cron: '0 18 * * *'  # This line means every day at 10am PST.
  workflow_dispatch:

jobs:
  sendEmail:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v3

      - name: Install dependencies
        run: npm i

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2' # Not needed with a .ruby-version file
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
  
      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v4
        
      - name: Build with Jekyll
        # Outputs to the './_site' directory by default
        run: bundle exec jekyll build --baseurl "${{ steps.pages.outputs.base_path }}"
        env:
          JEKYLL_ENV: production

      - name: Send Email Update
        env:
          MAILCHIMP_API_KEY: ${{ secrets.MAILCHIMP_API_KEY }}
          MAILCHIMP_SERVER: ${{ secrets.MAILCHIMP_SERVER }}
          MAILCHIMP_LIST_ID: ${{ secrets.MAILCHIMP_LIST_ID }}
        run: node _scripts/rss-to-email.js

      - name: Commit last published update
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Update latest emailed post"
          commit_options: "--no-verify --signoff"
          commit_user_name: "hawkeyexl"
          commit_user_email: "hawkeyexl@gmail.com"
          